### ISSUE TITLE
update some cvss details

### ISSUE THREAD

**Issue by j---** [RiskBasedPrioritization/RiskBasedPrioritization.github.io#23]
Hi! 
On 
https://riskbasedprioritization.github.io/risk/Rbp_schemes/

It says CVSS B and BT and "Threat" but it's talking about CVSS v3 scores. In v3, it's "Temporal" and the "BT" naming schema wasn't defined yet. I think it makes a lot of sense to use the B and BT naming schema, but then it should say "CVSS v3" to clarify and use "temporal" instead of "threat". 
Sorry for the minor details. Hope that helps. 
Thanks!

**Comment by Crashedmind** [comment]
thanks - updated text and plots for clarity https://riskbasedprioritization.github.io/risk/Rbp_schemes/ 
thanks!
